include:
  package:lints/recommended.yaml

analyzer:
  exclude:
    - bricks/
    - build/**
    - lib/**.g.dart
    - test/**.g.dart

  plugins:
    - custom_lint

  errors:
    avoid_print: warning
    avoid_relative_lib_imports: warning
    always_use_package_imports: warning

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - comment_references
    - dangling_library_doc_comments
    - implicit_call_tearoffs
    - invalid_case_patterns
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - discarded_futures
    - always_put_required_named_parameters_first
    - always_put_control_body_on_new_line
    - avoid_escaping_inner_quotes
    - avoid_multiple_declarations_per_line
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - eol_at_end_of_file
    - leading_newlines_in_multiline_strings
    - noop_primitive_operations
    - prefer_expression_function_bodies
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_for_whitespace
    - sort_constructors_first
    - type_annotate_public_apis
    - unnecessary_final
    - unnecessary_lambdas
    - use_raw_strings
    - sort_pub_dependencies
    - secure_pubspec_urls
    - use_super_parameters
