name: error_case
description: A library to define error use cases for Dart.
version: 0.0.1

homepage: 'https://github.com/HirogaKatageri/error-case'
repository: 'https://github.com/HirogaKatageri/error-case'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

index_generator:
  default_name: index
  exclude:
    - '**.g.dart'
  indexes:
    - path: lib
      exclude:
        - 'exception/**'
      name: error_case
    - path: lib/exception
      name: error_case_exception
      include:
        - 'base/**'
        - 'field/**'
        - 'num/**'
        - 'string/**'
        - 'list/**'
        - 'map/**'