name: error_case
description: A library to define error use cases in Dart. Useful data class, string, min, max values and etc.
version: 0.1.0

homepage: 'https://github.com/HirogaKatageri/error-case'
repository: 'https://github.com/HirogaKatageri/error-case'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.0

index_generator:
  default_name: index
  exclude:
    - '**.g.dart'
  indexes:
    - path: lib
      exclude:
        - 'exception/**'
      name: error_case
    - path: lib/exception
      name: error_case_exception
      include:
        - 'base/**'
        - 'field/**'
        - 'num/**'
        - 'string/**'
        - 'list/**'
        - 'map/**'
